export {default as Navbar} from './Navbar';
export {default as Product} from './Product';
export {default as CategoryBox} from './CategoryBox';
export {default as CategoryMenu} from './CategoryMenu';
export {default as ContactView} from './ContactView';
export {default as Layout} from './Layout';
export {default as Footer} from './Footer';
export {default as HomePage} from './HomePage';
export {default as SearchPage} from './Searchpage';